// ─── Price formula helpers ────────────────────────────────────────────────────
// baseCost * scaleFactor^bought
export function calcPrice(baseCost, scaleFactor, bought) {
  return Math.floor(baseCost * Math.pow(scaleFactor, bought));
}

// ─── Click Upgrades ───────────────────────────────────────────────────────────
export const CLICK_UPGRADE_DEFS = [
  {
    key: "ClickUpgrade1",
    name: "Click Upgrade 1",
    icon: "⚡",
    desc: "Increments base click gain by +0.25 per level.",
    baseCost: 10,
    scaleFactor: 1.4,
    defaultMax: 10,
  },
  {
    key: "ClickUpgrade2",
    name: "Click Upgrade 2",
    icon: "🔥",
    desc: "Multiplies click gain by 1.25x per level.",
    baseCost: 75,
    scaleFactor: 1.6,
    defaultMax: 10,
  },
  {
    key: "ClickUpgrade3",
    name: "Click Upgrade 3",
    icon: "📈",
    desc: "Multiplies click gain based on current Click Points. More levels = stronger scaling.",
    baseCost: 300,
    scaleFactor: 1.8,
    defaultMax: 10,
  },
  {
    key: "ClickUpgrade4",
    name: "Click Upgrade 4",
    icon: "⏱️",
    desc: "Reduces click cooldown by 10% per level (multiplicative).",
    baseCost: 500,
    scaleFactor: 2.0,
    defaultMax: 10,
  },
  {
    key: "ClickUpgrade5",
    name: "Click Upgrade 5",
    icon: "💎",
    desc: "Multiplies click gain by 1.5x per level.",
    baseCost: 1000,
    scaleFactor: 2.2,
    defaultMax: 10,
  },
  {
    key: "ClickUpgrade6",
    name: "Click Upgrade 6",
    icon: "🌟",
    desc: "Increases base click gain by +1 per level.",
    baseCost: 2500,
    scaleFactor: 2.8,
    defaultMax: 10,
  },
  {
    key: "ClickUpgrade7",
    name: "Click Upgrade 7",
    icon: "🤖",
    desc: "Unlocks & speeds up the Auto Clicker. First level = 5s interval, each level reduces by 10%.",
    baseCost: 5000,
    scaleFactor: 2.5,
    defaultMax: 10,
  },
  {
    key: "ClickUpgrade8",
    name: "Click Upgrade 8",
    icon: "⏳",
    desc: "Boosts click gain based on time spent in current rebirth. Resets on rebirth.",
    baseCost: 8000,
    scaleFactor: 2.6,
    defaultMax: 10,
  },
  {
    key: "ClickUpgrade9",
    name: "Click Upgrade 9",
    icon: "🌀",
    desc: "+0.1 base gain, x1.1 click multiplier, and x1.1 rebirth gain per level.",
    baseCost: 15000,
    scaleFactor: 2.8,
    defaultMax: 10,
  },
  {
    key: "ClickUpgrade10",
    name: "Click Upgrade 10",
    icon: "🚀",
    desc: "Reduces click cooldown by 25% and auto clicker cooldown by 25% per level.",
    baseCost: 30000,
    scaleFactor: 3.0,
    defaultMax: 10,
  },
];

// ─── Rebirth Upgrades ─────────────────────────────────────────────────────────
export const REBIRTH_UPGRADE_DEFS = [
  {
    key: "RebirthUpgrade1",
    name: "Rebirth Upgrade 1",
    icon: "✨",
    desc: "+1 base click gain per level.",
    baseCost: 1,
    scaleFactor: 1.5,
    defaultMax: 20,
  },
  {
    key: "RebirthUpgrade2",
    name: "Rebirth Upgrade 2",
    icon: "📦",
    desc: "+5 max cap for Click Upgrade 1 per level.",
    baseCost: 2,
    scaleFactor: 1.6,
    defaultMax: 10,
  },
  {
    key: "RebirthUpgrade3",
    name: "Rebirth Upgrade 3",
    icon: "📦",
    desc: "+5 max cap for Click Upgrade 2 per level.",
    baseCost: 3,
    scaleFactor: 1.7,
    defaultMax: 10,
  },
  {
    key: "RebirthUpgrade4",
    name: "Rebirth Upgrade 4",
    icon: "💥",
    desc: "Unlocks the Big Click Button (50x normal clicks, 1 min cooldown).",
    baseCost: 5,
    scaleFactor: 1.0,
    defaultMax: 1,
  },
  {
    key: "RebirthUpgrade5",
    name: "Rebirth Upgrade 5",
    icon: "📦",
    desc: "+5 max cap for Click Upgrade 5 per level.",
    baseCost: 4,
    scaleFactor: 1.7,
    defaultMax: 10,
  },
  {
    key: "RebirthUpgrade6",
    name: "Rebirth Upgrade 6",
    icon: "⏩",
    desc: "Reduces Big Click Button cooldown by 5% per level.",
    baseCost: 6,
    scaleFactor: 1.8,
    defaultMax: 10,
  },
  {
    key: "RebirthUpgrade7",
    name: "Rebirth Upgrade 7",
    icon: "🌠",
    desc: "Rebirth Points gain x1.5 per level.",
    baseCost: 10,
    scaleFactor: 2.0,
    defaultMax: 10,
  },
];